version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_db

  backend:
    image: yuliakhalaeva/foodgram_api:latest
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_api

  frontend:
    image: yuliakhalaeva/foodgram_front:v1.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_front

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    container_name: foodgram_nginx

volumes:
  postgres_data:
  static_value:
  media_value: